name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5 # for using commit log
      - name: Test Local Action
        uses: ./
        with:
          webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}
          message1: 'test1 message'
          message2: 'test2 message'
          action-titles: 'github'
          action-urls: 'https://github.co.jp/'
          visible-changed-files: true

  test-action-min:
    name: GitHub Actions Test Min
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Test Local Action (no arguments)
        uses: ./
        with:
          webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}

  test-action-template:
    name: GitHub Actions Test Template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
      - name: Test Local Action (with template)
        uses: ./
        with:
          webhook-url: ${{ secrets.TEST_WEBHOOK_URL }}
          template: './.github/body-template.json'
          message1: 'test1 message'
          message2: 'test2 message'
          action-titles: |
            github
            docs
          action-urls: |
            https://github.co.jp/
            https://docs.github.com/ja
